#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <curl/curl.h>
#include "cJSON/cJSON.h"
#include <time.h>
#include "air_quality.h"
#include "send_email.h"

// Helper function to read existing JSON array from a file
cJSON* readExistingArray() {
    FILE* file = fopen("output.json", "r");
    if (file != NULL) {
        // Determine file size
        fseek(file, 0, SEEK_END);
        long fileSize = ftell(file);
        fseek(file, 0, SEEK_SET);

        // Allocate memory to file content
        char* fileContents = malloc(fileSize + 1);
        if (fileContents != NULL) {
            // Read file content into memory
            fread(fileContents, 1, fileSize, file);
            fclose(file);

            fileContents[fileSize] = '\0';

            // Parse existing JSON data
            cJSON* dataArray = cJSON_Parse(fileContents);
            free(fileContents);
            return dataArray;
        } else {
            fclose(file);
            fprintf(stderr, "Error allocating memory for file contents\n");
            return NULL;
        }
    }
    return NULL;
}
// Process each item in the JSON array
void processJsonItem(cJSON* jsonItem) {
    cJSON* list = cJSON_GetObjectItemCaseSensitive(jsonItem, "list");
    if (cJSON_IsArray(list)) {
        // Read existing JSON array from file
        cJSON* dataArray = readExistingArray();

        cJSON* listItem;
        cJSON_ArrayForEach(listItem, list) {
            cJSON* components = cJSON_GetObjectItemCaseSensitive(listItem, "components");
            if (cJSON_IsObject(components)) {
                // Add item to existing array or create a new array 
                if (cJSON_IsArray(dataArray)) {
                    cJSON_AddItemToArray(dataArray, cJSON_Duplicate(listItem, 1));
                } else {
                    dataArray = cJSON_CreateArray();
                    cJSON_AddItemToArray(dataArray, cJSON_Duplicate(listItem, 1));
                }

                // Extracting values
                double so2 = cJSON_GetObjectItemCaseSensitive(components, "so2")->valuedouble;
                double co = cJSON_GetObjectItemCaseSensitive(components, "co")->valuedouble;
                double o3 = cJSON_GetObjectItemCaseSensitive(components, "o3")->valuedouble;
                double no = cJSON_GetObjectItemCaseSensitive(components, "no")->valuedouble;

                // Getting current date and time
                time_t rawtime;
                struct tm* timeinfo;
                char buffer[80];

                time(&rawtime);
                timeinfo = localtime(&rawtime);

                strftime(buffer, sizeof(buffer), "%Y-%m-%d %H:%M:%S", timeinfo);
                printf("Current Date and Time: %s\n", buffer);

                // Save values to a text file
                FILE* txtFile = fopen("output.txt", "a"); // Open in append mode
                if (txtFile != NULL) {
                    fprintf(txtFile, "Date and Time: %s\n", buffer);
                    fprintf(txtFile, "CO: %.2f\n", co);
                    fprintf(txtFile, "SO2: %.2f\n", so2);
                    fprintf(txtFile, "NO: %.2f\n", no);
                    fprintf(txtFile, "O3: %.2f\n", o3);
                    fprintf(txtFile, "\n");
                    fclose(txtFile);
                    printf("Data saved to output.txt\n");
                } else {
                    fprintf(stderr, "Error opening output.txt for writing\n");
                }
                
                // Call comparison functions
                int so2Result = compare_so2(so2);
                int noResult = compare_no(no);
                int o3Result = compare_o3(o3);
                char airFilename[100];
                sprintf(airFilename, "air_%s.txt", buffer);
                // Create a new text file with the computed values
                FILE* airFile = fopen(airFilename, "w");
                if (airFile != NULL) {
                    fprintf(airFile,"\t\t\t\t\t\t\t\t\t\t\tTHE AIR QUALITY REPORT \t\t\t\t\t\t\t\t\t\t\t\n");
                    fprintf(airFile,"=======================================================================================================================\n");
                    fprintf(airFile, "Date and Time: %s\n", buffer);
                    fprintf(airFile, "1.SO2 Comparison Result: %d\n", so2Result);
                    fprintf(airFile, "2.NO Comparison Result: %d\n", noResult);
                    fprintf(airFile, "3.O3 Comparison Result: %d\n", o3Result);
                    fprintf(airFile,"KEYWORDS:\n\tSO2 = Sulphur Dioxide(range<=350)\n\tNO = Nitrogen Monoxide(range: 0.1 to 100)\n\tO3 = Ozone(range<=180)\n");
                    fprintf(airFile,"NOTE: This report is generated by computer so no signature is required");
                    fclose(airFile);
                    printf("Computed values saved to air_currentdata.txt\n");
                } else {
                    fprintf(stderr, "Error opening air_currentdata.txt for writing\n");
                }

                // Check for anomalies and create anomaly.txt if any anomaly is detected
                if (so2Result == -1 || noResult == -1 || o3Result == -1) {
                    const char *subject = "Anomaly Detected in Air Quality";
                    const char *body = "Anomaly detected in the Air Quality. Please take precautions";
                    const char *attachment = "anomaly.txt";
                    FILE* anomalyFile = fopen("anomaly.txt", "w");
                    if (anomalyFile != NULL) {
                        fprintf(anomalyFile,"\t\t\t\t\t\t\t\t\t\t\tTHE AIR QUALITY REPORT \t\t\t\t\t\t\t\t\t\t\t\n");
                        fprintf(airFile, "Date and Time: %s\n", buffer);
                        fprintf(anomalyFile, "Anomaly is Detected in the weather please be save!\n");
                        fprintf(anomalyFile,"PRECAUTIONS/SAFETY MEASURES:\n");
                        fprintf(anomalyFile,"\t1.Reduce the time you spend outdoors to under 30 minutes.\n\t2.Reduce the intensity of outdoor activity.According the EPA, the chances of being affected by the air quality increases if a person stays outdoor for long time in tedious activity.\n");
                        fprintf(anomalyFile,"\t3.If you have to go outdoor, where masks. (usually N95 or KN95 are recommended).\n\t4.Keep your air indoor healty by closing windows and doors.\n\t5.Use HEPA air cleaner is appreciated");
                        fprintf(anomalyFile,"Disclaimer: IF YOU FEEL SUFFOCATION PLEASE CONSULT TO DOCTOR");
                        fclose(anomalyFile);
                        printf("Anomaly detected. Information saved to anomaly.txt\n");
                        // Send email notification with attachment
                        sendEmail(subject,body,attachment);
                    } else {
                        fprintf(stderr, "Error opening anomaly.txt for writing\n");
                    }
                }
            } else {
                fprintf(stderr, "Error extracting 'components' from JSON item:\n%s\n", cJSON_Print(listItem));
            }
        }

        cJSON_Delete(dataArray);
    } else {
        fprintf(stderr, "Error: 'list' is not an array in the JSON item:\n%s\n", cJSON_Print(jsonItem));
    }
}
size_t WriteCallback(void* contents, size_t size, size_t nmemb, void* userp) {
    size_t realsize = size * nmemb;
    printf("%.*s", (int)realsize, (char*)contents);

    cJSON* json = cJSON_Parse((char*)contents);

    if (json != NULL) {
        if (cJSON_IsArray(json)) {
            cJSON* jsonItem;
            cJSON_ArrayForEach(jsonItem, json) {
                processJsonItem(jsonItem);
            }
        } else {
            processJsonItem(json);
        }

        cJSON_Delete(json);
    } else {
        fprintf(stderr, "Error parsing JSON\n");
    }

    return realsize;
}
int main() {
    CURL* curl = curl_easy_init();
    if (!curl) {
        fprintf(stderr, "Error initializing libcurl\n");
        return 1;
    }

    const char* url = "http://api.openweathermap.org/data/2.5/air_pollution?lat=24.8607&lon=67.0011&appid=d485a877d60ae98bcc2131ef64c80858";
    curl_easy_setopt(curl, CURLOPT_URL, url);
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, NULL);

    CURLcode res = curl_easy_perform(curl);
    if (res != CURLE_OK) {
        fprintf(stderr, "curl_easy_perform() failed: %s\n", curl_easy_strerror(res));
    }
    
    curl_easy_cleanup(curl);

    return 0;
}



